
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: test


jwt:
  ACCESS_SECRET_KEY: "agijdahgfjksljklKNJBHBDgkldjflasjionhrjean1jvasfdsafajkfdsknskfjioa"
  REFRESH_SECRET_KEY: "dagjukKLFJDfldkjsiodhsg854nksdnagjbabgfhadsjhgiueuhjHFISGHiHiurhighrHGUJ"